services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-library}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-librarypass}
      POSTGRES_DB: ${POSTGRES_DB:-librarydb}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - db
    env_file: .env
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      # Pass through values for SQLAlchemy
      POSTGRES_USER: ${POSTGRES_USER:-library}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-librarypass}
      POSTGRES_DB: ${POSTGRES_DB:-librarydb}
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    restart: unless-stopped

volumes:
  db-data:
